### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by penihel** [ThatBlokeCalledJay/auto-app-version#3]
##[debug]Evaluating condition for step: 'Auto app version'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Auto app version
==============================================================================
Task         : Auto App Version
Description  : A build and release task for automatically incrementing an app's version
Version      : 1.0.12
Author       : ThatBlokeCalledJay
Help         : [More Information](https://github.com/ThatBlokeCalledJay/auto-app-version/wiki)
==============================================================================
##[debug]VstsTaskSdk 0.1 commit _COMMIT_HASH_
##[debug]Entering D:\a\_tasks\AutoAppVersion_5c7da804-4989-4055-b709-444c6b6be219\1.0.12\task.ps1.
##[debug]INPUT_DEVOPSPAT: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'
##[debug]INPUT_VERSIONVARIABLE: 'IgrejasNetVersion'
##[debug]INPUT_PROJECTFILE: 'D:\a\1\s\src\IgrejasNet.Application\IgrejasNet.Application.csproj'
##[debug]INPUT_SETASSEMBLYVERSION: 'true'
##[debug]INPUT_SETFILEVERSION: 'true'
##[debug]INPUT_STOPONNOMASK: 'false'
##[debug]INPUT_STOPONDOWNGRADE: 'false'
##[debug]INPUT_STOPONINVALIDEVARNAME: 'false'
##[debug]INPUT_ENVVARNAME (empty)
ProjectFile          : D:\a\1\s\src\IgrejasNet.Application\IgrejasNet.Application.csproj
VersionVariable      : IgrejasNetVersion
DevOpsPAT            : ***
DevOps Uri           : https://brtrust.visualstudio.com/
Project Name         : IgrejasNet
Project Id           : 649d5bac-c2f9-4a56-94a5-eacec3604101
BuildId              : 103
==============================================================================
Reading project file: D:\a\1\s\src\IgrejasNet.Application\IgrejasNet.Application.csproj.
Valid Version Mask Found: '0.0.$'
Trying to retrieve build with the url: https://brtrust.visualstudio.com/IgrejasNet/_apis/build/builds/103?api-version=4.1.
##[debug]GET https://brtrust.visualstudio.com/IgrejasNet/_apis/build/builds/103?api-version=4.1 with 0-byte payload
##[debug]received 4784-byte response of content type application/json; charset=utf-8; api-version=4.1
Trying to retrieve the build definition with the url: https://brtrust.visualstudio.com/IgrejasNet/_apis/build/definitions/3?api-version=4.1.
##[debug]GET https://brtrust.visualstudio.com/IgrejasNet/_apis/build/definitions/3?api-version=4.1 with 0-byte payload
##[debug]received 9602-byte response of content type application/json; charset=utf-8; api-version=4.1
VersionVariable 'IgrejasNetVersion' Found: '0.0.4' (current value)
==============================================================================
> Version Pattern: 0.0.$
-> Current App version: 0.0.4
--> New App Version: 0.0.5
==============================================================================
Trying to update VersionVariable 'IgrejasNetVersion' with the url: https://brtrust.visualstudio.com/IgrejasNet/_apis/build/definitions/3?api-version=4.1.
##[debug]PUT https://brtrust.visualstudio.com/IgrejasNet/_apis/build/definitions/3?api-version=4.1 with -1-byte payload
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"This request expects an object in the request body, but the supplied data could not be deserialized.","typeName":"Microsoft.TeamFoundation.Build.WebApi.RequestContentException, Microsoft.TeamFoundation.Build2.WebApi","typeKey":"RequestContentException","errorCode":0,"eventId":3000}
##[debug]At D:\a\_tasks\AutoAppVersion_5c7da804-4989-4055-b709-444c6b6be219\1.0.12\task.ps1:323 char:1
##[debug]+ Invoke-RestMethod -Method Put -Uri $defUri -Headers $devOpsHeader -Co ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, D:\a\_tasks\AutoAppVersion_5c7da804-4989-4055-b709-444c6b6be219\1.0.12\task.ps1: line 323
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Net.WebException: The remote server returned an error: (400) Bad Request.
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[error]The remote server returned an error: (400) Bad Request.
##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (400) Bad Request.
##[debug]Processed: ##vso[task.complete result=Failed]
##[section]Finishing: Auto app version

**Comment by ThatBlokeCalledJay** [comment]
I'm looking into this.

**Comment by ThatBlokeCalledJay** [comment]
Fixed with commit f1ccff1f2b829cea3eb88c72b40355f9520280cd. Pending feedback.

**Comment by ThatBlokeCalledJay** [comment]
Fix (f1ccff1f2b829cea3eb88c72b40355f9520280cd) released under version 1.0.13
