### ISSUE TITLE
Could it be used to add a git tag to the commit being built?

### ISSUE THREAD

**Issue by set-webmaster** [ThatBlokeCalledJay/auto-app-version#7]
Hi there, as the title says, I'd like to know if there would be a way to use this task to create a git tag for the commit that's being built by the pipeline. 

I tried setting the build name using the `AutoAppVersion` but it runs before the actual task and then returns the previously built version number...

**Comment by ThatBlokeCalledJay** [comment]
I'm afraid not. That is beyond the scope of this guy.
