### ISSUE TITLE
##[error]Method invocation failed because [System.Xml.XmlElement] does not contain a method named 'split'.

### ISSUE THREAD

**Issue by sbollap1** [ThatBlokeCalledJay/auto-app-version#8]
I am seeing the below error when i try to run on a windows agent in azure pipeline. any ideas on how to resolve this

Starting: Auto App Version
==============================================================================
Task         : Auto App Version
Description  : A build and release task for automatically incrementing an app's version.
Version      : 1.0.16
Author       : ThatBlokeCalledJay
Help         : [More Information](https://github.com/ThatBlokeCalledJay/auto-app-version/wiki)
==============================================================================
ProjectFile          : D:\a\1\s\xxx\xxx\ababab.csproj
VersionVariable      : Version
PAT                         : ***
DevOps Uri           : https://dev.azure.com/MyDevOps/
Project Name         : KKGKTI
Project Id           : 87655-76gfd-kjhy6-9988-fffffff
BuildId              : 7777
==============================================================================
Reading project file: D:\a\1\s\xxx\xxxx\ababb.csproj.
error:Method invocation failed because System.Xml.XmlElement does not contain a method named "split".
Finishing: Auto App Version

**Comment by ThatBlokeCalledJay** [comment]
From what little info you have provided, I'm guessing you've not quite configured you're files as detailed in the readme and there's some kind of variation. That being said, I'd like the task to report this correctly so will look into this area for better error reporting. If you get chance to provide a little more detail, e.g your project file (the property group with the version definition), that would be awesome.

**Comment by ThatBlokeCalledJay** [comment]
No response or other reports of this bug.
